### ISSUE TITLE
Cobblemon Quests [1.1.11 - Fabric] Required Dependency Forge 

### ISSUE THREAD

**Issue by NFLD99** [WinterWolfSV/Cobblemon_Quests#12]
FTB Quests (Forge) is a Required Dependency on Cobblemon Quests [1.1.11 - Fabric]

**Comment by WinterWolfSV** [comment]
I'm unable to replicate the issue you're describing. Could you please attach a crash log as well and I'll take a look at it?

**Comment by NFLD99** [comment]
![zIUXhmbdZ9](https://github.com/user-attachments/assets/ba8557d3-8fe6-4e7b-a3c4-45026c04f303)

**Comment by WinterWolfSV** [comment]
I haven't used that launcher before, but I think it is because I added ftb quests as required mods on curseforge. I have changed it now to not depend on both the fabric and forge version of ftb quests. The .jar in itself shouldn't have this issue. If the problem still occurs, please let me know in here again.
