### ISSUE TITLE
Certain players cannot connect to server because of Cobblemon Quests 1.1.6

### ISSUE THREAD

**Issue by CasualJeremy** [WinterWolfSV/Cobblemon_Quests#4]
A number of players on my server are unable to connect to the server and are getting the error shown below
 ![IMG_8934.jpg](https://github.com/WinterWolfSV/Cobblemon_Quests/assets/39568213/d7e40afe-e3a0-49b6-80f8-fb6def3c500d)

![cobblemonquests.PNG](https://github.com/WinterWolfSV/Cobblemon_Quests/assets/39568213/80693b41-93d3-47df-917a-63d2289d19c1)

They have the right version number downloaded.

 It's a private modpacks I've compiled and I have no issues getting in myself

**Comment by WinterWolfSV** [comment]
Hey! Sorry about that, it was a new feature I tried implementing in the latest version, but because of limited testing I also decided to implement a sort of failsafe. Run the command ´/cobblemonquestsconfig doVersionVerification false´ in the console and the issue should be resolved. I will work on a better implementation of this in future versions.
